right_format = '$all'
format = '$directory$line_break$character'

[aws]
symbol = ' '

[character]
success_symbol = "[›](bold green)"
error_symbol = "[›](bold red)"
vimcmd_symbol = "[‹](bold green)"
vimcmd_replace_one_symbol = "[‹](bold purple)"
vimcmd_replace_symbol = "[‹](bold purple)"
vimcmd_visual_symbol = "[‹](bold yellow)"

[directory]
truncate_to_repo = false

[git_branch]
symbol = ' '

[golang]
symbol = ' '

[haskell]
symbol = ' '

[jobs]
symbol = ' '

[lua]
symbol = ' '

[nodejs]
symbol = ' '

[java]
symbol = ' '

[package]
symbol = '󰏗 '

[python]
symbol = ' '

[ruby]
symbol = ' '

[rust]
symbol = ' '

[docker_context]
symbol = ' '
